name: Deploy Sonopresta to OVH (SFTP)

on:
  push:
    branches: [ main ]        # déploie à chaque push sur main
  workflow_dispatch:           # permet aussi de lancer manuellement si besoin

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ton site n'a pas de build → on pousse simplement le contenu de ./www
      # (si un jour tu ajoutes un build, on l'activera ici)

      - name: Upload /www to OVH via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          server: ${{ secrets.OVH_HOST }}
          username: ${{ secrets.OVH_USER }}
          password: ${{ secrets.OVH_PASSWORD }}
          local_path: ./www                 # <<< IMPORTANT : on envoie UNIQUEMENT ./www
          remote_path: ${{ secrets.OVH_TARGET_DIR }}   # /home/sonoprf/www
          sftp_only: true
          exclude: ".git*,node_modules*,.github*,*.md,*.map"

      # (Optionnel) petit healthcheck HTTP : change l'URL si besoin
      - name: Healthcheck homepage
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://www.sonopresta.com/)
          if [ "$STATUS" != "200" ]; then
            echo "Healthcheck failed with status $STATUS"
            exit 1
          fi
