name: Deploy Sonopresta to OVH (SFTP via lftp)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Mirror dist -> OVH
        env:
          OVH_HOST: ${{ secrets.OVH_HOST }}
          OVH_USER: ${{ secrets.OVH_USER }}
          OVH_PASSWORD: ${{ secrets.OVH_PASSWORD }}
        run: |
          set -e
          lftp -u "$OVH_USER","$OVH_PASSWORD" sftp://$OVH_HOST -e "
            set sftp:auto-confirm yes
            set net:max-retries 2
            set net:timeout 20
            mirror -R \
              --parallel=4 \
              --only-newer \
              --delete \
              --exclude-glob '.git*' \
              --exclude-glob '.github*' \
              --exclude-glob 'node_modules*' \
              --exclude-glob '*.map' \
              --exclude-glob '.env*' \
              dist /home/$OVH_USER/www
            bye
          "

      - name: Healthcheck
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://sonopresta.com/)
          [ "$STATUS" = "200" ] || (echo "Healthcheck failed: $STATUS" && exit 1)
          curl -I https://sonopresta.com/assets/
