name: Deploy Sonopresta to OVH (SFTP)

on:
  push:
    branches: [ main ]           # déploie à chaque push sur main
  workflow_dispatch:              # permet un lancement manuel

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Déploiement SFTP avec mot de passe (action officielle)
      - name: Deploy to OVH via SFTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: ${{ secrets.OVH_HOST }}
          username: ${{ secrets.OVH_USER }}
          password: ${{ secrets.OVH_PASSWORD }}
          protocol: sftp
          port: 22
          local-dir: ./www/          # on envoie UNIQUEMENT le contenu de ./www
          server-dir: /www/          # côté OVH: dossier racine du site
          dangerous-clean-slate: false
          state-name: .ftp-deploy-sync-state-sonopresta.json
          exclude: |
            **/.git*
            **/.github*
            **/node_modules*
            **/*.md
            **/*.map
            **/.env*
            **/.DS_Store

      # (Optionnel) Healthcheck
      - name: Healthcheck homepage
        if: ${{ success() && secrets.SITE_URL != '' }}
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${{ secrets.SITE_URL }}")
          if [ "$STATUS" != "200" ]; then
            echo "Healthcheck failed with status $STATUS"
            exit 1
          fi
