name: Deploy Sonopresta to OVH (SFTP)

on:
  push:
    branches: [ main ]          # déploie à chaque push sur main
  workflow_dispatch:             # permet un lancement manuel

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Déploiement SFTP avec mot de passe (action fiable)
      - name: Deploy to OVH via SFTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: ${{ secrets.OVH_HOST }}
          username: ${{ secrets.OVH_USER }}
          password: ${{ secrets.OVH_PASSWORD }}
          protocol: sftp
          port: 22
          # On envoie UNIQUEMENT le contenu du dossier www de ton repo
          local-dir: ./www/
          # Côté OVH, le login te place dans /home/sonoprf
          # donc le site public est /home/sonoprf/www -> ici on met simplement /www/
          server-dir: /www/
          # On ne supprime rien côté serveur (plus safe pour démarrer)
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.github*
            **/node_modules*
            **/*.md
            **/*.map
            **/.env*
            **/.DS_Store
